<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<RootNamespace>System.Text.Markdown</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<VersionPrefix>1.4.0</VersionPrefix>
		<PackageId>PeterJuhasz.Text.Markdown</PackageId>
		<PackageTags>markdown</PackageTags>
		<PackageProjectUrl>https://github.com/Peter-Juhasz/markdown</PackageProjectUrl>
		<RepositoryUrl>https://github.com/Peter-Juhasz/markdown</RepositoryUrl>
	</PropertyGroup>
	
	<PropertyGroup>
		<IsTrimmable>true</IsTrimmable>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<InvariantGlobalization>true</InvariantGlobalization>
		<EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
		<EnableUnsafeUTF7Encoding>false</EnableUnsafeUTF7Encoding>
		<WarningsNotAsErrors>IL2026</WarningsNotAsErrors>
	</PropertyGroup>
	<PropertyGroup Condition="$(Configuration) == 'Release'">
		<TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="PeterJuhasz.Extensions" Version="2.*-*" />
	</ItemGroup>

</Project>
